# Site settings
title: "ETOOBUSY"
description: "ðŸš€ minimal blogging for the impatient"
baseurl: "/ETOOBUSY"
url: ""
author: "polettix"

# Build settings
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: ETOOBUSY

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME" ]
